SELECT TITLE, b.BOARD_ID as BOARD_ID, REPLY_ID, r.WRITER_ID as WRITER_ID, r.CONTENTS as CONTENTS, DATE_FORMAT(r.CREATED_DATE, '%Y-%m-%d') as CREATED_DATE
FROM USED_GOODS_BOARD b 
JOIN USED_GOODS_REPLY r
ON r.BOARD_ID=b.BOARD_ID
WHERE DATE_FORMAT(b.CREATED_DATE, "%Y-%m") = "2022-10"
ORDER BY r.CREATED_DATE, TITLE;


